[build]
  publish = "dist"
  command = "npm run build"

[plugins]

  [netlify-plugin-hashfiles]
    [config]
    entryPoints = [
      "dist/*.html"
    ]
    staticDir = "/static/"
    canonicalRoot = "https://practical-panini-b62059.netlify.com/"
